
[[main]]
name = "domů"
pageRef = "/"
weight = 10

[[main]]
name = "blog"
pageRef = "Blog"
weight = 20

[[main]]
name = "projekty"
pageRef = "Projects"
weight = 30

[[main]]
name = "prodávám"
pageRef = "Selling"
weight = 40

[[main]]
name = "kontakt"
pageRef = "Contact"
weight = 50

