# Main menu which appears below site header.
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Writings"
url = "/posts"
weight = 2

[[main]]
name = "Tags"
url = "/tags"
weight = 3

[[main]]
name = "About"
url = "/about"
weight = 4